server:
  port:8080

nacos:
  config:
    server-addr: 127.0.0.1:18848 # Nacos ?????
    bootstrap:
      enable: true # ???? Nacos ??????????? false?
      log-enable: true # ???? Nacos ??????????????? false?
    data-id: example # ??? Nacos ???? dataId?
    type: YAML # ??? Nacos ???????????? PROPERTIES?
    group: DEFAULT_GROUP # ??? Nacos ???????? DEFAULT_GROUP?
    namespace: # ??? Nacos ????????? null?
